### ISSUE TITLE
Pretrained weights and instructions to run?

### ISSUE THREAD

**Issue by Luffy03** [EndoluminalSurgicalVision-IMR/Medical-SSL#1]
Thanks for your nice work first.
Would you plan to release the pre-trained weights and provide details about how to run your code?

**Comment by chuyan99** [comment]
We have updated the detailed instructions to pretrain the SSL pretext tasks and fine-tune the target model.

**Comment by chuyan99** [comment]
We have updated the detailed instructions to pretrain the SSL pretext tasks and fine-tune the target model, please refer to ReadME.

**Comment by Luffy03** [comment]
Thanks! It will help me a lot!
