### ISSUE TITLE
Excellent work! Some explanations regarding strong augmentation effect

### ISSUE THREAD

**Issue by yliu1229** [EndoluminalSurgicalVision-IMR/Medical-SSL#4]
Thank you for the excellent review and work, i would like to express my gratitude to yous.

One point to mention is that there are already convincing explanations regarding strong augmentation diminishes the value of SSL pretraining: medical images are very different from natural images in that strong augmentations could severely corrupt the semantic meaning of medical images. Some works, e.g. Shih-Cheng Huang, et al. Self-supervised learning for medical image classification: a systematic review and implementation guidelines. npj Digit. Medicine, 2023, have discussed this in detail.

**Comment by yungu-imr** [comment]
Many thanks for your comments!
